# 서버 포트 설정
server:
  port: 8080
spring:
  jpa:

    hibernate:
      ddl-auto: validate
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  h2:
    console:
      enabled: true



logging:
  level:
    org.hibernate.SQL: debug # hibernate에서 생성하는 sql을 logger을 이용해서 보는 설정
    org.hibernate.orm.jdbc.bind: trace  # hibernate 에서 쿼리 파라 미터를 ?에서 실제로 보는 설정